### ISSUE TITLE
Add support for specifying a Python package in appmap.yml

### ISSUE THREAD

**Issue by apotterri** [applandinc/appmap-python#48]
Analogous to `appmap-ruby`'s `gem` support: https://github.com/applandinc/appmap-ruby#configuration .

```yaml
name: my-app
packages:
- package: pyyaml
```
would add the modules from the `pyyaml` package, and turn on shallow mode for the modules.
